package Biblioteca;


/**
 * Biblioteca/_GestionBibliotecaStub.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from Biblioteca.idl
 * domingo 11 de mayo de 2025 11H43' CEST
 */

public class _GestionBibliotecaStub extends org.omg.CORBA.portable.ObjectImpl implements Biblioteca.GestionBiblioteca
{

    public String obtenerLibro (String titulo)
    {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request ("obtenerLibro", true);
            $out.write_string (titulo);
            $in = _invoke ($out);
            String $result = $in.read_string ();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream ();
            String _id = $ex.getId ();
            throw new org.omg.CORBA.MARSHAL (_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return obtenerLibro (titulo        );
        } finally {
            _releaseReply ($in);
        }
    } // obtenerLibro

    public void agregarLibro (String titulo, String autor)
    {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request ("agregarLibro", true);
            $out.write_string (titulo);
            $out.write_string (autor);
            $in = _invoke ($out);
            return;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream ();
            String _id = $ex.getId ();
            throw new org.omg.CORBA.MARSHAL (_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            agregarLibro (titulo, autor        );
        } finally {
            _releaseReply ($in);
        }
    } // agregarLibro

    public String buscarPorAutor (String autor)
    {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request ("buscarPorAutor", true);
            $out.write_string (autor);
            $in = _invoke ($out);
            String $result = $in.read_string ();
            return $result;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream ();
            String _id = $ex.getId ();
            throw new org.omg.CORBA.MARSHAL (_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            return buscarPorAutor (autor        );
        } finally {
            _releaseReply ($in);
        }
    } // buscarPorAutor

    public void eliminarLibro (String titulo)
    {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            org.omg.CORBA.portable.OutputStream $out = _request ("eliminarLibro", true);
            $out.write_string (titulo);
            $in = _invoke ($out);
            return;
        } catch (org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream ();
            String _id = $ex.getId ();
            throw new org.omg.CORBA.MARSHAL (_id);
        } catch (org.omg.CORBA.portable.RemarshalException $rm) {
            eliminarLibro (titulo        );
        } finally {
            _releaseReply ($in);
        }
    } // eliminarLibro

    // Type-specific CORBA::Object operations
    private static String[] __ids = {
            "IDL:Biblioteca/GestionBiblioteca:1.0"};

    public String[] _ids ()
    {
        return (String[])__ids.clone ();
    }

    private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
    {
        String str = s.readUTF ();
        String[] args = null;
        java.util.Properties props = null;
        org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
        try {
            org.omg.CORBA.Object obj = orb.string_to_object (str);
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
            _set_delegate (delegate);
        } finally {
            orb.destroy() ;
        }
    }

    private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
    {
        String[] args = null;
        java.util.Properties props = null;
        org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
        try {
            String str = orb.object_to_string (this);
            s.writeUTF (str);
        } finally {
            orb.destroy() ;
        }
    }
} // class _GestionBibliotecaStub
