package Biblioteca;


/**
 * Biblioteca/GestionBibliotecaPOA.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from Biblioteca.idl
 * domingo 11 de mayo de 2025 11H43' CEST
 */

public abstract class GestionBibliotecaPOA extends org.omg.PortableServer.Servant
        implements Biblioteca.GestionBibliotecaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("obtenerLibro", new java.lang.Integer (0));
    _methods.put ("agregarLibro", new java.lang.Integer (1));
    _methods.put ("buscarPorAutor", new java.lang.Integer (2));
    _methods.put ("eliminarLibro", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                                      org.omg.CORBA.portable.InputStream in,
                                                      org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
      case 0:  // Biblioteca/GestionBiblioteca/obtenerLibro
      {
        String titulo = in.read_string ();
        String $result = null;
        $result = this.obtenerLibro (titulo);
        out = $rh.createReply();
        out.write_string ($result);
        break;
      }

      case 1:  // Biblioteca/GestionBiblioteca/agregarLibro
      {
        String titulo = in.read_string ();
        String autor = in.read_string ();
        this.agregarLibro (titulo, autor);
        out = $rh.createReply();
        break;
      }

      case 2:  // Biblioteca/GestionBiblioteca/buscarPorAutor
      {
        String autor = in.read_string ();
        String $result = null;
        $result = this.buscarPorAutor (autor);
        out = $rh.createReply();
        out.write_string ($result);
        break;
      }

      case 3:  // Biblioteca/GestionBiblioteca/eliminarLibro
      {
        String titulo = in.read_string ();
        this.eliminarLibro (titulo);
        out = $rh.createReply();
        break;
      }

      default:
        throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
          "IDL:Biblioteca/GestionBiblioteca:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionBiblioteca _this()
  {
    return GestionBibliotecaHelper.narrow(
            super._this_object());
  }

  public GestionBiblioteca _this(org.omg.CORBA.ORB orb)
  {
    return GestionBibliotecaHelper.narrow(
            super._this_object(orb));
  }


} // class GestionBibliotecaPOA
