package Biblioteca;


/**
 * Biblioteca/GestionBibliotecaOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from Biblioteca.idl
 * domingo 11 de mayo de 2025 11H43' CEST
 */

public interface GestionBibliotecaOperations
{
  String obtenerLibro (String titulo);
  void agregarLibro (String titulo, String autor);
  String buscarPorAutor (String autor);
  void eliminarLibro (String titulo);
} // interface GestionBibliotecaOperations
