package Biblioteca;


/**
 * Biblioteca/GestionBiblioteca.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from Biblioteca.idl
 * domingo 11 de mayo de 2025 11H43' CEST
 */

public interface GestionBiblioteca extends GestionBibliotecaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface GestionBiblioteca
